'use client';

import { useState } from 'react';
import { Activity, ArrowDownRight, ArrowUpRight, Bell, BriefcaseBusiness, CalendarDays, ChevronDown, CircleDollarSign, Clock3, FileText, LayoutDashboard, Menu, MoreHorizontal, Plus, Search, Settings, Users, WalletCards, X } from 'lucide-react';

type NavItem = { label: string; icon: React.ElementType };
const nav: NavItem[] = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Employees', icon: Users }, { label: 'Payroll', icon: WalletCards }, { label: 'Leave & attendance', icon: CalendarDays }, { label: 'Documents', icon: FileText }
];
const employees = [
  { name: 'Aisha Al Mansoori', role: 'Product Designer', dept: 'Design', status: 'Active', initials: 'AA', color: 'peach', salary: 'AED 18,500' },
  { name: 'Omar Khalid', role: 'Senior Engineer', dept: 'Engineering', status: 'Active', initials: 'OK', color: 'blue', salary: 'AED 24,000' },
  { name: 'Maya Fernandes', role: 'HR Business Partner', dept: 'People', status: 'On leave', initials: 'MF', color: 'purple', salary: 'AED 16,200' },
  { name: 'Daniel Wong', role: 'Finance Analyst', dept: 'Finance', status: 'Active', initials: 'DW', color: 'green', salary: 'AED 14,800' },
  { name: 'Sara Al Hashimi', role: 'Account Executive', dept: 'Sales', status: 'Active', initials: 'SA', color: 'yellow', salary: 'AED 12,500' }
];

function Stat({ title, value, change, icon: Icon, tone }: { title: string; value: string; change: string; icon: React.ElementType; tone: string }) {
  return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={20} /></div><div className="stat-copy"><span>{title}</span><strong>{value}</strong><small className={change.startsWith('+') ? 'up' : 'neutral'}>{change}</small></div></div>;
}

export default function Home() {
  const [active, setActive] = useState('Overview');
  const [menu, setMenu] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const [query, setQuery] = useState('');
  const filtered = employees.filter(e => `${e.name} ${e.role} ${e.dept}`.toLowerCase().includes(query.toLowerCase()));
  return <main className="shell">
    <aside className={menu ? 'sidebar mobile-open' : 'sidebar'}>
      <div className="brand"><div className="brand-mark">O</div><span>orbit<span className="brand-accent">.</span></span></div>
      <div className="workspace"><div className="workspace-avatar">AC</div><div><b>Acme Corporation</b><small>Dubai, UAE</small></div><ChevronDown size={15} /></div>
      <nav><p className="nav-label">Workspace</p>{nav.map(item => <button key={item.label} className={active === item.label ? 'nav-item selected' : 'nav-item'} onClick={() => { setActive(item.label); setMenu(false); }}><item.icon size={18} /><span>{item.label}</span>{item.label === 'Leave & attendance' && <i>4</i>}</button>)}<p className="nav-label space">Manage</p><button className="nav-item"><Settings size={18} /><span>Settings</span></button></nav>
      <div className="sidebar-bottom"><div className="help-card"><div className="help-dot">?</div><div><b>Need a hand?</b><small>Visit our help center</small></div><ArrowUpRight size={15} /></div><div className="profile"><div className="avatar small">JM</div><div><b>Jordan Mitchell</b><small>Administrator</small></div><MoreHorizontal size={18} /></div></div>
    </aside>
    <section className="content"><header><button className="mobile-menu" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button><div className="breadcrumbs"><span>Workspace</span><b>/</b><strong>{active}</strong></div><div className="header-actions"><button className="icon-button"><Bell size={19} /><i></i></button><div className="avatar">JM</div></div></header>
      <div className="page"><div className="page-heading"><div><p className="eyebrow">Tuesday, 24 September 2024</p><h1>Good morning, Jordan <span>✦</span></h1><p className="subheading">Here’s what’s happening with your people today.</p></div><button className="primary" onClick={() => setShowModal(true)}><Plus size={18} /> Add employee</button></div>
        <div className="stats"><Stat title="Total employees" value="248" change="+12 this month" icon={Users} tone="lavender" /><Stat title="Monthly payroll" value="AED 1.84M" change="+4.8% vs last month" icon={CircleDollarSign} tone="mint" /><Stat title="Pending approvals" value="18" change="Needs your attention" icon={Clock3} tone="peach" /><Stat title="Attendance today" value="96.4%" change="+1.2% vs last week" icon={Activity} tone="sky" /></div>
        <div className="grid-main"><section className="panel payroll-panel"><div className="panel-heading"><div><h2>Payroll overview</h2><p>Monthly payroll spend</p></div><button className="select">2024 <ChevronDown size={14} /></button></div><div className="chart"><div className="chart-y"><span>AED 2M</span><span>AED 1.5M</span><span>AED 1M</span><span>AED 500K</span><span>AED 0</span></div><div className="chart-area"><div className="grid-lines"><i></i><i></i><i></i><i></i><i></i></div><svg viewBox="0 0 650 190" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#7c6cf2" stopOpacity=".25"/><stop offset="1" stopColor="#7c6cf2" stopOpacity="0"/></linearGradient></defs><path d="M0 138 C35 135 50 145 80 124 S128 129 155 105 S195 120 225 96 S263 101 290 83 S330 95 360 70 S400 89 435 60 S480 77 510 48 S555 64 590 35 S620 42 650 25 L650 190 L0 190Z" fill="url(#fill)"/><path d="M0 138 C35 135 50 145 80 124 S128 129 155 105 S195 120 225 96 S263 101 290 83 S330 95 360 70 S400 89 435 60 S480 77 510 48 S555 64 590 35 S620 42 650 25" fill="none" stroke="#7162e8" strokeWidth="3" /></svg><div className="months"><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span><span>Oct</span><span>Nov</span><span>Dec</span></div></div></div><div className="chart-legend"><span><i className="legend-dot purple"></i>Gross payroll</span><span><i className="legend-dot pale"></i>Budget</span><b><ArrowUpRight size={14} /> 8.2% <em>year to date</em></b></div></section>
          <section className="panel approvals"><div className="panel-heading"><div><h2>Needs your attention</h2><p>Items waiting for approval</p></div><button className="text-button">View all <ArrowUpRight size={15} /></button></div><div className="approval-list"><div className="approval"><div className="approval-icon leave"><CalendarDays size={18} /></div><div><b>Leave request</b><span>Maya Fernandes · 3 days</span></div><button className="round-arrow">→</button></div><div className="approval"><div className="approval-icon expense"><FileText size={18} /></div><div><b>Expense claim</b><span>Omar Khalid · AED 1,240</span></div><button className="round-arrow">→</button></div><div className="approval"><div className="approval-icon contract"><BriefcaseBusiness size={18} /></div><div><b>Contract renewal</b><span>Daniel Wong · Due in 5 days</span></div><button className="round-arrow">→</button></div></div><div className="approval-footer"><span><strong>18</strong> items pending</span><span className="avatars"><i>OK</i><i>MF</i><i>SA</i><b>+15</b></span></div></section></div>
        <section className="panel people-panel"><div className="panel-heading"><div><h2>People</h2><p>Your recently added employees</p></div><div className="people-actions"><div className="search"><Search size={17} /><input placeholder="Search people" value={query} onChange={e => setQuery(e.target.value)} /></div><button className="filter">Filter <ChevronDown size={14} /></button><button className="text-button">View directory <ArrowUpRight size={15} /></button></div></div><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Department</th><th>Status</th><th>Monthly salary</th><th></th></tr></thead><tbody>{filtered.map(e => <tr key={e.name}><td><div className="person"><div className={`avatar ${e.color}`}>{e.initials}</div><div><b>{e.name}</b><span>{e.role}</span></div></div></td><td>{e.dept}</td><td><span className={e.status === 'Active' ? 'status active' : 'status leave'}><i></i>{e.status}</span></td><td className="salary">{e.salary}</td><td><button className="dots"><MoreHorizontal size={18} /></button></td></tr>)}</tbody></table></div></section>
      </div>
    </section>
    {showModal && <div className="modal-backdrop" onClick={() => setShowModal(false)}><div className="modal" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={() => setShowModal(false)}><X size={18} /></button><div className="modal-icon"><Users size={21} /></div><h2>Add an employee</h2><p>Create a profile for a new member of your team.</p><label>Full name<input placeholder="e.g. Alex Morgan" autoFocus /></label><label>Work email<input type="email" placeholder="alex@company.com" /></label><div className="modal-row"><label>Department<select><option>Engineering</option><option>Design</option><option>People</option><option>Finance</option></select></label><label>Monthly salary<input placeholder="AED 0.00" /></label></div><div className="modal-actions"><button className="secondary" onClick={() => setShowModal(false)}>Cancel</button><button className="primary" onClick={() => setShowModal(false)}>Create profile</button></div></div></div>}
  </main>;
}
