'use client';

import { useState } from 'react';

const documents = [
  { title: 'September 2024 payslip', type: 'Payslip', employee: 'Aisha Al Mansoori', date: '30 Sep 2024' },
  { title: 'Annual leave request', type: 'Leave form', employee: 'Maya Fernandes', date: '24 Sep 2024' },
  { title: 'Salary confirmation letter', type: 'HR letter', employee: 'Omar Khalid', date: '12 Sep 2024' },
];

export default function DocumentsPage() {
  const [selected, setSelected] = useState(documents[0]);
  return <main className="page-shell"><div className="content-panel wide-panel">
    <div className="panel-header"><div><p className="eyebrow">Printable records</p><h1>Documents</h1></div><a href="/" className="secondary-action">Back to dashboard</a></div>
    <div className="documents-layout"><section><div className="toolbar-row"><div><h2 className="section-title">Document library</h2><p className="muted">Print-ready HR and payroll documents.</p></div></div><div className="document-list">{documents.map((document) => <button className={selected.title === document.title ? 'document-row selected' : 'document-row'} key={document.title} onClick={() => setSelected(document)}><span className="document-icon">▤</span><span><strong>{document.title}</strong><small>{document.type} · {document.employee}</small></span><small>{document.date}</small></button>)}</div></section><section className="print-preview"><div className="preview-actions"><span>Print preview</span><button className="primary-button" onClick={() => window.print()}>Print document</button></div><article className="print-sheet"><div className="document-brand"><strong>orbit<span>.</span></strong><small>Acme Corporation · Dubai, UAE</small></div><hr /><p className="eyebrow">{selected.type}</p><h2>{selected.title}</h2><div className="document-meta"><p><span>Employee</span><strong>{selected.employee}</strong></p><p><span>Document date</span><strong>{selected.date}</strong></p></div><div className="document-copy"><p>This document has been prepared by Acme Corporation for official HR records.</p><div className="document-line" /><div className="document-line short" /></div><footer>Generated by Orbit HR · UAE operations</footer></article></section></div>
  </div></main>;
}
